// src/components/tools/CalendarAvailabilityFinder.svelte
<script lang="ts">
  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  interface TimeSlot {
    start: number;
    end: number;
  }

  interface Person {
    id: string;
    name: string;
    busySlots: TimeSlot[];
  }

  let { locale, translations }: Props = $props();

  function t(key: string): string {
    const scope =
      (translations['tools']['calendar-availability-finder'] as Record<string, unknown>) || {};
    const keys = key.split('.');
    let value: unknown = scope;

    for (const part of keys) {
      value = (value as Record<string, unknown>)?.[part];
    }

    return typeof value === 'string'
      ? value
      : `MISSING: tools.calendar-availability-finder.${key}`;
  }

  function tCommon(key: string): string {
    const scope = (translations['tools'] as Record<string, unknown>) || {};
    const keys = key.split('.');
    let value: unknown = scope;

    for (const part of keys) {
      value = (value as Record<string, unknown>)?.[part];
    }

    return typeof value === 'string' ? value : `MISSING: tools.${key}`;
  }

  function parseTimeToMinutes(value: string): number {
    const [hours, minutes] = value.split(':').map((part) => Number.parseInt(part, 10));
    if (!Number.isFinite(hours) || !Number.isFinite(minutes)) {
      return 0;
    }

    return hours * 60 + minutes;
  }

  function formatMinutesToTime(value: number): string {
    const safeValue = Math.max(0, Math.min(24 * 60, Math.round(value)));
    const hours = Math.floor(safeValue / 60)
      .toString()
      .padStart(2, '0');
    const minutes = (safeValue % 60).toString().padStart(2, '0');
    return `${hours}:${minutes}`;
  }

  function mergeBusySlots(slots: TimeSlot[]): TimeSlot[] {
    const sorted = [...slots]
      .filter((slot) => slot.end > slot.start)
      .sort((left, right) => left.start - right.start);

    if (sorted.length === 0) {
      return [];
    }

    const merged: TimeSlot[] = [sorted[0]];
    for (const slot of sorted.slice(1)) {
      const current = merged[merged.length - 1];
      if (slot.start <= current.end) {
        current.end = Math.max(current.end, slot.end);
      } else {
        merged.push({ ...slot });
      }
    }

    return merged;
  }

  function findAvailableSlots(
    people: Person[],
    workStart: number,
    workEnd: number,
    minimumDuration: number
  ): TimeSlot[] {
    const dayStart = Math.min(workStart, workEnd);
    const dayEnd = Math.max(workStart, workEnd);
    const mergedBusy = mergeBusySlots(
      people.flatMap((person) =>
        person.busySlots
          .map((slot) => ({
            start: Math.max(slot.start, dayStart),
            end: Math.min(slot.end, dayEnd),
          }))
          .filter((slot) => slot.end > slot.start)
      )
    );

    const available: TimeSlot[] = [];
    let cursor = dayStart;

    for (const slot of mergedBusy) {
      if (slot.start - cursor >= minimumDuration) {
        available.push({ start: cursor, end: slot.start });
      }
      cursor = Math.max(cursor, slot.end);
    }

    if (dayEnd - cursor >= minimumDuration) {
      available.push({ start: cursor, end: dayEnd });
    }

    return available;
  }

  let people = $state<Person[]>([
    {
      id: '1',
      name: 'Alice',
      busySlots: [
        { start: 540, end: 600 },
        { start: 780, end: 840 },
      ],
    },
    {
      id: '2',
      name: 'Bob',
      busySlots: [
        { start: 600, end: 660 },
        { start: 900, end: 960 },
      ],
    },
    {
      id: '3',
      name: 'Carol',
      busySlots: [
        { start: 540, end: 570 },
        { start: 720, end: 780 },
      ],
    },
  ]);

  let workStartInput = $state('09:00');
  let workEndInput = $state('17:00');
  let duration = $state(30);
  let newSlotStart = $state('09:00');
  let newSlotEnd = $state('10:00');
  let selectedPerson = $state('1');
  let copied = $state(false);
  let timerRef = $state<ReturnType<typeof setTimeout> | null>(null);

  let availableSlots = $derived.by(() =>
    findAvailableSlots(
      people,
      parseTimeToMinutes(workStartInput),
      parseTimeToMinutes(workEndInput),
      Math.max(15, Number(duration) || 0)
    )
  );

  let timelineTicks = $derived.by(() => {
    const start = parseTimeToMinutes(workStartInput);
    const end = parseTimeToMinutes(workEndInput);
    const safeEnd = Math.max(start + 60, end);
    const ticks: string[] = [];

    for (let current = start; current <= safeEnd; current += 60) {
      ticks.push(formatMinutesToTime(current));
    }

    return ticks;
  });

  function addPerson() {
    const nextIndex = people.length + 1;
    people = [
      ...people,
      {
        id: crypto.randomUUID(),
        name: `Person ${nextIndex}`,
        busySlots: [],
      },
    ];
  }

  function updatePersonName(id: string, name: string) {
    people = people.map((person) => (person.id === id ? { ...person, name } : person));
  }

  function removePerson(id: string) {
    people = people.filter((person) => person.id !== id);
    if (selectedPerson === id) {
      selectedPerson = people[0]?.id || '';
    }
  }

  function addBusySlot() {
    if (!selectedPerson) {
      return;
    }

    const start = parseTimeToMinutes(newSlotStart);
    const end = parseTimeToMinutes(newSlotEnd);
    if (start >= end) {
      return;
    }

    people = people.map((person) =>
      person.id === selectedPerson
        ? {
            ...person,
            busySlots: mergeBusySlots([...person.busySlots, { start, end }]),
          }
        : person
    );
  }

  function removeBusySlot(personId: string, slotIndex: number) {
    people = people.map((person) =>
      person.id === personId
        ? {
            ...person,
            busySlots: person.busySlots.filter((_, index) => index !== slotIndex),
          }
        : person
    );
  }

  async function copySlots() {
    const output = availableSlots
      .map((slot) => `${formatMinutesToTime(slot.start)} ${t('to')} ${formatMinutesToTime(slot.end)}`)
      .join('\n');

    await navigator.clipboard.writeText(output);
    copied = true;
    if (timerRef) {
      clearTimeout(timerRef);
    }
    timerRef = setTimeout(() => {
      copied = false;
    }, 2000);
  }
</script>

<div class="space-y-6">
  <div class="grid gap-4 md:grid-cols-3">
    <label class="space-y-2">
      <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('workHoursStart')}</span>
      <input
        bind:value={workStartInput}
        type="time"
        class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
      />
    </label>
    <label class="space-y-2">
      <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('workHoursEnd')}</span>
      <input
        bind:value={workEndInput}
        type="time"
        class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
      />
    </label>
    <label class="space-y-2">
      <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('minDuration')}</span>
      <input
        bind:value={duration}
        type="number"
        min="15"
        step="15"
        class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
      />
    </label>
  </div>

  <div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-900/40">
    <h3 class="text-sm font-semibold uppercase tracking-wide text-gray-600 dark:text-gray-300">
      {t('participantsBusyTimes')}
    </h3>
    <button
      onclick={addPerson}
      class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
    >
      {t('addPerson')}
    </button>
  </div>

  <div class="grid gap-4 lg:grid-cols-2">
    {#each people as person (person.id)}
      <section class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-900/40">
        <div class="mb-3 flex items-center gap-3">
          <input
            value={person.name}
            onchange={(event) => updatePersonName(person.id, event.currentTarget.value)}
            class="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
          />
          <button
            onclick={() => removePerson(person.id)}
            class="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600 transition-colors hover:bg-red-50 dark:border-red-800 dark:text-red-300 dark:hover:bg-red-900/20"
          >
            {tCommon('remove')}
          </button>
        </div>

        {#if person.busySlots.length > 0}
          <div class="space-y-2">
            {#each person.busySlots as slot, index (index)}
              <div class="flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-sm dark:bg-gray-800">
                <span class="font-mono text-gray-700 dark:text-gray-200">
                  {formatMinutesToTime(slot.start)} {t('to')} {formatMinutesToTime(slot.end)}
                </span>
                <button
                  onclick={() => removeBusySlot(person.id, index)}
                  class="text-red-600 hover:text-red-700 dark:text-red-300"
                >
                  {tCommon('remove')}
                </button>
              </div>
            {/each}
          </div>
        {:else}
          <p class="text-sm text-gray-500 dark:text-gray-400">{t('noBusyTimes')}</p>
        {/if}
      </section>
    {/each}
  </div>

  <section class="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40">
    <h3 class="mb-4 text-sm font-semibold uppercase tracking-wide text-gray-600 dark:text-gray-300">
      {t('addBusyTime')}
    </h3>
    <div class="grid gap-4 md:grid-cols-[minmax(0,1fr),1fr,1fr,auto]">
      <label class="space-y-2">
        <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('selectPerson')}</span>
        <select
          bind:value={selectedPerson}
          class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
        >
          {#each people as person (person.id)}
            <option value={person.id}>{person.name}</option>
          {/each}
        </select>
      </label>
      <label class="space-y-2">
        <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('workHoursStart')}</span>
        <input
          bind:value={newSlotStart}
          type="time"
          class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
        />
      </label>
      <label class="space-y-2">
        <span class="text-sm font-medium text-gray-700 dark:text-gray-300">{t('workHoursEnd')}</span>
        <input
          bind:value={newSlotEnd}
          type="time"
          class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-800 dark:text-white"
        />
      </label>
      <div class="flex items-end">
        <button
          onclick={addBusySlot}
          class="w-full rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-black dark:bg-blue-600 dark:hover:bg-blue-700"
        >
          {t('addBusyTime')}
        </button>
      </div>
    </div>
  </section>

  <section class="rounded-xl border border-green-200 bg-green-50 p-4 dark:border-green-900/40 dark:bg-green-900/10">
    <div class="mb-4 flex items-center justify-between gap-3">
      <h3 class="text-lg font-semibold text-green-900 dark:text-green-100">{t('availableSlots')}</h3>
      <button
        onclick={copySlots}
        disabled={availableSlots.length === 0}
        class="rounded-lg border border-green-300 px-3 py-2 text-sm font-medium text-green-700 transition-colors hover:bg-green-100 disabled:cursor-not-allowed disabled:opacity-50 dark:border-green-700 dark:text-green-200 dark:hover:bg-green-900/30"
      >
        {copied ? tCommon('copied') : tCommon('copy')}
      </button>
    </div>

    {#if availableSlots.length > 0}
      <div class="mb-4 flex flex-wrap gap-2">
        {#each availableSlots as slot (slot.start)}
          <div class="rounded-full bg-white px-3 py-2 text-sm font-mono text-gray-700 shadow-sm dark:bg-gray-800 dark:text-gray-100">
            {formatMinutesToTime(slot.start)} {t('to')} {formatMinutesToTime(slot.end)}
          </div>
        {/each}
      </div>

      <div class="space-y-3">
        <div class="flex justify-between text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400">
          {#each timelineTicks as tick (tick)}
            <span>{tick}</span>
          {/each}
        </div>
        <div class="relative h-16 rounded-xl bg-white shadow-inner dark:bg-gray-800">
          {#each availableSlots as slot (slot.start)}
            <div
              class="absolute top-3 h-10 rounded-lg bg-green-500/80 px-2 text-xs font-medium text-white"
              style={`left: ${((slot.start - parseTimeToMinutes(workStartInput)) / Math.max(parseTimeToMinutes(workEndInput) - parseTimeToMinutes(workStartInput), 1)) * 100}%; width: ${((slot.end - slot.start) / Math.max(parseTimeToMinutes(workEndInput) - parseTimeToMinutes(workStartInput), 1)) * 100}%`}
            >
              <span class="block truncate pt-3">{formatMinutesToTime(slot.start)} - {formatMinutesToTime(slot.end)}</span>
            </div>
          {/each}
        </div>
      </div>
    {:else}
      <div class="space-y-1 text-sm text-gray-600 dark:text-gray-300">
        <p>{t('noAvailableSlots')}</p>
        <p>{t('tryAdjusting')}</p>
      </div>
    {/if}
  </section>
</div>

// src/components/tools/CalendarAvailabilityFinder.tsx
'use client';

import { useState, useCallback, useMemo } from 'react';
import { useTranslations } from 'next-intl';

interface TimeSlot {
  start: number;
  end: number;
}

interface Person {
  id: string;
  name: string;
  busySlots: TimeSlot[];
}

function parseTimeToMinutes(time: string): number {
  const [hours, minutes] = time.split(':').map(Number);
  return hours * 60 + minutes;
}

function formatMinutesToTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}`;
}

function findAvailableSlots(people: Person[], workStart: number, workEnd: number, duration: number): TimeSlot[] {
  const allBusy: TimeSlot[] = [];
  
  people.forEach(person => {
    person.busySlots.forEach(slot => {
      allBusy.push(slot);
    });
  });
  
  allBusy.sort((a, b) => a.start - b.start);
  
  const merged: TimeSlot[] = [];
  for (const slot of allBusy) {
    if (merged.length === 0 || merged[merged.length - 1].end < slot.start) {
      merged.push({ ...slot });
    } else {
      merged[merged.length - 1].end = Math.max(merged[merged.length - 1].end, slot.end);
    }
  }
  
  const available: TimeSlot[] = [];
  let current = workStart;
  
  for (const busy of merged) {
    if (busy.start > current && busy.start - current >= duration) {
      available.push({ start: current, end: busy.start });
    }
    current = Math.max(current, busy.end);
  }
  
  if (workEnd > current && workEnd - current >= duration) {
    available.push({ start: current, end: workEnd });
  }
  
  return available;
}

export default function CalendarAvailabilityFinder() {
  const t = useTranslations('tools.calendar-availability-finder');
  const tCommon = useTranslations('tools');
  const [people, setPeople] = useState<Person[]>([
    { id: '1', name: 'Alice', busySlots: [{ start: 540, end: 600 }, { start: 780, end: 840 }] },
    { id: '2', name: 'Bob', busySlots: [{ start: 600, end: 660 }, { start: 900, end: 960 }] },
    { id: '3', name: 'Carol', busySlots: [{ start: 540, end: 570 }, { start: 720, end: 780 }] },
  ]);
  const [workStart, setWorkStart] = useState(540);
  const [workEnd, setWorkEnd] = useState(1020);
  const [duration, setDuration] = useState(30);
  const [newSlotStart, setNewSlotStart] = useState('09:00');
  const [newSlotEnd, setNewSlotEnd] = useState('10:00');
  const [selectedPerson, setSelectedPerson] = useState('');
  const [copied, setCopied] = useState(false);

  const addPerson = useCallback(() => {
    setPeople(prev => [...prev, {
      id: Date.now().toString(),
      name: `Person ${prev.length + 1}`,
      busySlots: [],
    }]);
  }, []);

  const updatePersonName = useCallback((id: string, name: string) => {
    setPeople(prev => prev.map(p => p.id === id ? { ...p, name } : p));
  }, []);

  const removePerson = useCallback((id: string) => {
    setPeople(prev => prev.filter(p => p.id !== id));
  }, []);

  const addBusySlot = useCallback(() => {
    if (!selectedPerson) return;
    const start = parseTimeToMinutes(newSlotStart);
    const end = parseTimeToMinutes(newSlotEnd);
    if (start >= end) return;
    
    setPeople(prev => prev.map(p => {
      if (p.id === selectedPerson) {
        return { ...p, busySlots: [...p.busySlots, { start, end }].sort((a, b) => a.start - b.start) };
      }
      return p;
    }));
  }, [selectedPerson, newSlotStart, newSlotEnd]);

  const removeBusySlot = useCallback((personId: string, slotIdx: number) => {
    setPeople(prev => prev.map(p => {
      if (p.id === personId) {
        return { ...p, busySlots: p.busySlots.filter((_, i) => i !== slotIdx) };
      }
      return p;
    }));
  }, []);

  const availableSlots = useMemo(() => 
    findAvailableSlots(people, workStart, workEnd, duration),
    [people, workStart, workEnd, duration]
  );

  const handleCopy = useCallback(() => {
    const text = availableSlots.map(slot => 
      `${formatMinutesToTime(slot.start)} - ${formatMinutesToTime(slot.end)}`
    ).join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [availableSlots]);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap gap-4 items-end">
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-1">{t('workHoursStart')}</label>
          <select
            value={workStart}
            onChange={(e) => setWorkStart(parseInt(e.target.value))}
            className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            {Array.from({ length: 24 }, (_, i) => i * 60).map(m => (
              <option key={m} value={m}>{formatMinutesToTime(m)}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-1">{t('workHoursEnd')}</label>
          <select
            value={workEnd}
            onChange={(e) => setWorkEnd(parseInt(e.target.value))}
            className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            {Array.from({ length: 24 }, (_, i) => i * 60).map(m => (
              <option key={m} value={m}>{formatMinutesToTime(m)}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-xs text-gray-500 dark:text-gray-400 mb-1">{t('minDuration')}</label>
          <select
            value={duration}
            onChange={(e) => setDuration(parseInt(e.target.value))}
            className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            {[15, 30, 45, 60, 90, 120].map(d => (
              <option key={d} value={d}>{d} min</option>
            ))}
          </select>
        </div>
        <button onClick={addPerson} className="px-3 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700">
          {t('addPerson')}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div>
          <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">{t('participantsBusyTimes')}</h3>
          <div className="space-y-3">
            {people.map(person => (
              <div key={person.id} className="p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
                <div className="flex gap-2 items-center mb-2">
                  <input
                    type="text"
                    value={person.name}
                    onChange={(e) => updatePersonName(person.id, e.target.value)}
                    className="flex-1 px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  />
                  <button onClick={() => removePerson(person.id)} className="text-red-500 hover:text-red-700">✕</button>
                </div>
                <div className="flex flex-wrap gap-1">
                  {person.busySlots.map((slot, idx) => (
                    <span key={idx} className="inline-flex items-center gap-1 text-xs px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded">
                      {formatMinutesToTime(slot.start)} - {formatMinutesToTime(slot.end)}
                      <button onClick={() => removeBusySlot(person.id, idx)} className="hover:text-red-900">×</button>
                    </span>
                  ))}
                  {person.busySlots.length === 0 && (
                    <span className="text-xs text-gray-400">{t('noBusyTimes')}</span>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
            <h4 className="text-xs font-medium text-blue-700 dark:text-blue-300 mb-2">{t('addBusyTime')}</h4>
            <div className="flex flex-wrap gap-2 items-center">
              <select
                value={selectedPerson}
                onChange={(e) => setSelectedPerson(e.target.value)}
                className="px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
              >
                <option value="">{t('selectPerson')}</option>
                {people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
              <input
                type="time"
                value={newSlotStart}
                onChange={(e) => setNewSlotStart(e.target.value)}
                className="px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
              />
              <span className="text-gray-500">{t('to')}</span>
              <input
                type="time"
                value={newSlotEnd}
                onChange={(e) => setNewSlotEnd(e.target.value)}
                className="px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
              />
              <button
                onClick={addBusySlot}
                disabled={!selectedPerson}
                className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
              >
                {tCommon('add')}
              </button>
            </div>
          </div>
        </div>

        <div>
          <div className="flex justify-between items-center mb-3">
            <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300">
              {t('availableSlots')} ({availableSlots.length})
            </h3>
            <button onClick={handleCopy} className="text-sm text-blue-600 hover:text-blue-700 dark:text-blue-400">
              {copied ? tCommon('copied') : tCommon('copy')}
            </button>
          </div>
          
          {availableSlots.length > 0 ? (
            <div className="space-y-2">
              {availableSlots.map((slot, idx) => {
                const slotDuration = slot.end - slot.start;
                return (
                  <div key={idx} className="p-3 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
                    <div className="flex justify-between items-center">
                      <span className="font-medium text-green-700 dark:text-green-300">
                        {formatMinutesToTime(slot.start)} - {formatMinutesToTime(slot.end)}
                      </span>
                      <span className="text-sm text-green-600 dark:text-green-400">
                        {slotDuration >= 60 ? `${Math.floor(slotDuration / 60)}h ${slotDuration % 60}m` : `${slotDuration}m`}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg text-center">
              <p className="text-yellow-700 dark:text-yellow-300">{t('noAvailableSlots')}</p>
              <p className="text-xs text-yellow-600 dark:text-yellow-400 mt-1">{t('tryAdjusting')}</p>
            </div>
          )}

          <div className="mt-4 p-3 bg-gray-50 dark:bg-gray-900 rounded-lg">
            <h4 className="text-xs font-medium text-gray-700 dark:text-gray-300 mb-2">{t('timeline')}</h4>
            <div className="relative h-8 bg-gray-200 dark:bg-gray-700 rounded overflow-hidden">
              {people.map((person, pIdx) => 
                person.busySlots.map((slot, sIdx) => {
                  const left = ((slot.start - workStart) / (workEnd - workStart)) * 100;
                  const width = ((slot.end - slot.start) / (workEnd - workStart)) * 100;
                  return (
                    <div
                      key={`${pIdx}-${sIdx}`}
                      className="absolute h-full bg-red-400 dark:bg-red-600 opacity-50"
                      style={{ left: `${Math.max(0, left)}%`, width: `${Math.min(100 - left, width)}%` }}
                      title={`${person.name}: ${formatMinutesToTime(slot.start)} - ${formatMinutesToTime(slot.end)}`}
                    />
                  );
                })
              )}
              {availableSlots.map((slot, idx) => {
                const left = ((slot.start - workStart) / (workEnd - workStart)) * 100;
                const width = ((slot.end - slot.start) / (workEnd - workStart)) * 100;
                return (
                  <div
                    key={idx}
                    className="absolute h-full bg-green-400 dark:bg-green-600 opacity-70"
                    style={{ left: `${left}%`, width: `${width}%` }}
                  />
                );
              })}
            </div>
            <div className="flex justify-between text-xs text-gray-500 mt-1">
              <span>{formatMinutesToTime(workStart)}</span>
              <span>{formatMinutesToTime(workEnd)}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
