// src/components/tools/CaseConverter.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  let { locale, translations }: Props = $props();

  // Translation helpers
  function t(key: string): string {
    const scope = translations['tools']['case'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.case.${key}`;
  }
  function tg(key: string): string {
    const scope = translations['tools'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.${key}`;
  }

  let input = $state('');

  let copied = $state('');

  let timerRef = $state(null);  onDestroy(() => {
    if (timerRef) clearTimeout(timerRef);
  });

  // Functions
  const conversions = [
    { id: 'upper', label: t('uppercase'), fn: (s: string) => s.toUpperCase() },
    { id: 'lower', label: t('lowercase'), fn: (s: string) => s.toLowerCase() },
    { id: 'title', label: t('titleCase'), fn: (s: string) => s.replace(/\w\S*/g, txt => txt.charAt(0).toUpperCase() + txt.slice(1).toLowerCase()) },
    { id: 'sentence', label: t('sentenceCase'), fn: (s: string) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase() },
    { id: 'camel', label: t('camelCase'), fn: (s: string) => s.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()) },
    { id: 'pascal', label: 'PascalCase', fn: (s: string) => s.toLowerCase().replace(/(?:^|[^a-zA-Z0-9]+)(.)/g, (_, c) => c.toUpperCase()) },
    { id: 'snake', label: t('snakeCase'), fn: (s: string) => s.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '') },
    { id: 'kebab', label: 'kebab-case', fn: (s: string) => s.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') },
  ];
  async function copyResult(id: string, text: string) {
    await navigator.clipboard.writeText(text);
    copied = id;
    setTimeout(() => copied = '', 2000);
  }

</script>

<div class="space-y-6">
  <textarea
    bind:value={input}
    class="w-full h-40 px-4 py-3 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg text-gray-900 dark:text-white"
    placeholder={tg('inputPlaceholder')}
  ></textarea>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
    {#each conversions as conversion (conversion.id)}
      {@const result = conversion.fn(input)}
      <div class="p-3 bg-gray-100 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg">
        <div class="flex justify-between items-center mb-2">
          <span class="text-sm font-medium text-amber-600 dark:text-amber-400">{conversion.label}</span>
          <button
            onclick={() => copyResult(conversion.id, result)}
            class={`text-xs px-2 py-1 rounded ${copied === conversion.id ? 'btn-success' : 'bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100'}`}
          >
            {copied === conversion.id ? tg('copied') : tg('copy')}
          </button>
        </div>
        <div class="text-sm break-all text-gray-900 dark:text-gray-100">{result}</div>
      </div>
    {/each}
  </div>
</div>

// src/components/tools/CaseConverter.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';

export default function CaseConverter() {
  const t = useTranslations('tools.case');
  const tg = useTranslations('tools');
  const [input, setInput] = useState('');
  const [copied, setCopied] = useState('');

  const conversions = [
    { id: 'upper', label: t('uppercase'), fn: (s: string) => s.toUpperCase() },
    { id: 'lower', label: t('lowercase'), fn: (s: string) => s.toLowerCase() },
    { id: 'title', label: t('titleCase'), fn: (s: string) => s.replace(/\w\S*/g, txt => txt.charAt(0).toUpperCase() + txt.slice(1).toLowerCase()) },
    { id: 'sentence', label: t('sentenceCase'), fn: (s: string) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase() },
    { id: 'camel', label: t('camelCase'), fn: (s: string) => s.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()) },
    { id: 'pascal', label: 'PascalCase', fn: (s: string) => s.toLowerCase().replace(/(?:^|[^a-zA-Z0-9]+)(.)/g, (_, c) => c.toUpperCase()) },
    { id: 'snake', label: t('snakeCase'), fn: (s: string) => s.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '') },
    { id: 'kebab', label: 'kebab-case', fn: (s: string) => s.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') },
  ];

  const copyResult = async (id: string, text: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(''), 2000);
  };

  return (
    <div className="space-y-4">
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">{tg('input')}</label>
        <textarea
          className="tool-textarea"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={t('placeholder')}
        />
      </div>

      <button onClick={() => setInput('')} className="btn-secondary">
        {tg('clear')}
      </button>

      {input && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {conversions.map(({ id, label, fn }) => {
            const result = fn(input);
            return (
              <div key={id} className="p-3 bg-gray-100 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-400">{label}</span>
                  <button
                    onClick={() => copyResult(id, result)}
                    className={`text-xs px-2 py-1 rounded ${copied === id ? 'bg-green-600 text-white' : 'bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100'}`}
                  >
                    {copied === id ? tg('copied') : tg('copy')}
                  </button>
                </div>
                <div className="text-sm break-all text-gray-900 dark:text-gray-100">{result}</div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
