// src/components/tools/JsonToSwift.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';

export default function JsonToSwift() {
  const t = useTranslations('tools.json-to-swift');
  const [input, setInput] = useState('{\n  "id": 1,\n  "name": "John Doe",\n  "email": "john@example.com",\n  "isActive": true,\n  "tags": ["developer", "designer"],\n  "address": {\n    "street": "123 Main St",\n    "city": "New York"\n  }\n}');
  const [output, setOutput] = useState('');
  const [structName, setStructName] = useState('Root');
  const [useCodable, setUseCodable] = useState(true);

  const toCamelCase = (str: string): string => {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  };

  const toPascalCase = (str: string): string => {
    const camel = toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  };

  const getSwiftType = (value: unknown, key: string, structs: Map<string, string>): string => {
    if (value === null) return 'Any?';
    if (typeof value === 'string') return 'String';
    if (typeof value === 'number') {
      return Number.isInteger(value) ? 'Int' : 'Double';
    }
    if (typeof value === 'boolean') return 'Bool';
    if (Array.isArray(value)) {
      if (value.length === 0) return '[Any]';
      const itemType = getSwiftType(value[0], key, structs);
      return `[${itemType}]`;
    }
    if (typeof value === 'object') {
      const nestedStructName = toPascalCase(key);
      generateStruct(value as Record<string, unknown>, nestedStructName, structs);
      return nestedStructName;
    }
    return 'Any';
  };

  const generateStruct = (obj: Record<string, unknown>, name: string, structs: Map<string, string>) => {
    const lines: string[] = [];
    const protocol = useCodable ? ': Codable' : '';
    lines.push(`struct ${name}${protocol} {`);
    
    for (const [key, value] of Object.entries(obj)) {
      const propName = toCamelCase(key);
      const swiftType = getSwiftType(value, key, structs);
      lines.push(`    let ${propName}: ${swiftType}`);
    }
    
    lines.push('}');
    structs.set(name, lines.join('\n'));
  };

  const convert = () => {
    try {
      const parsed = JSON.parse(input);
      const structs = new Map<string, string>();
      
      if (Array.isArray(parsed)) {
        if (parsed.length > 0 && typeof parsed[0] === 'object') {
          generateStruct(parsed[0] as Record<string, unknown>, structName, structs);
        }
      } else if (typeof parsed === 'object' && parsed !== null) {
        generateStruct(parsed as Record<string, unknown>, structName, structs);
      }
      
      const result = Array.from(structs.values()).reverse().join('\n\n');
      setOutput(result);
    } catch {
      setOutput(t('errorInvalidJson'));
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('structName')}</label>
          <input type="text" value={structName} onChange={(e) => setStructName(e.target.value)}
            className="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white" />
        </div>
        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 text-gray-600 dark:text-gray-300">
            <input type="checkbox" checked={useCodable} onChange={(e) => setUseCodable(e.target.checked)}
              className="rounded bg-gray-200 dark:bg-gray-700 border-gray-300 dark:border-gray-600" />
            {t('useCodable')}
          </label>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('input')}</label>
          <textarea value={input} onChange={(e) => setInput(e.target.value)}
            className="w-full h-80 px-4 py-3 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white font-mono text-sm"
            placeholder={t('inputPlaceholder')} />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('output')}</label>
          <textarea value={output} readOnly
            className="w-full h-80 px-4 py-3 bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white font-mono text-sm"
            placeholder={t('outputPlaceholder')} />
        </div>
      </div>

      <div className="flex gap-4">
        <button onClick={convert}
          className="px-6 py-2 bg-orange-600 hover:bg-orange-700 text-white rounded-lg font-medium transition-colors">
          {t('convert')}
        </button>
        <button onClick={copyToClipboard} disabled={!output}
          className="px-6 py-2 bg-gray-200 dark:bg-gray-600 hover:bg-gray-300 dark:hover:bg-gray-500 text-gray-900 dark:text-white disabled:opacity-50 rounded-lg font-medium transition-colors">
          {t('copy')}
        </button>
      </div>
    </div>
  );
}

// src/components/tools/JsonToSwift.svelte
<script lang="ts">
  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  let { locale, translations }: Props = $props();

  // Translation helpers
  function t(key: string): string {
    const scope = translations['tools']['json-to-swift'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.json-to-swift.${key}`;
  }

  let input = $state('{\n  "id": 1,\n  "name": "John Doe",\n  "email": "john@example.com",\n  "isActive": true,\n  "tags": ["developer", "designer"],\n  "address": {\n    "street": "123 Main St",\n    "city": "New York"\n  }\n}');

  let output = $state('');

  let structName = $state('Root');

  let useCodable = $state(true);

  // Functions
  function toCamelCase(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }
  function toPascalCase(str: string): string {
    const camel = toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
  function getSwiftType(value: unknown, key: string, structs: Map<string, string>): string {
    if (value === null) return 'Any?';
    if (typeof value === 'string') return 'String';
    if (typeof value === 'number') {
      return Number.isInteger(value) ? 'Int' : 'Double';
    }
    if (typeof value === 'boolean') return 'Bool';
    if (Array.isArray(value)) {
      if (value.length === 0) return '[Any]';
      const itemType = getSwiftType(value[0], key, structs);
      return `[${itemType}]`;
    }
    if (typeof value === 'object') {
      const nestedStructName = toPascalCase(key);
      generateStruct(value as Record<string, unknown>, nestedStructName, structs);
      return nestedStructName;
    }
    return 'Any';
  }
  function generateStruct(obj: Record<string, unknown>, name: string, structs: Map<string, string>) {
    const lines: string[] = [];
    const protocol = useCodable ? ': Codable' : '';
    lines.push(`struct ${name}${protocol} {`);
    
    for (const [key, value] of Object.entries(obj)) {
      const propName = toCamelCase(key);
      const swiftType = getSwiftType(value, key, structs);
      lines.push(`    let ${propName}: ${swiftType}`);
    }
    
    lines.push('}');
    structs.set(name, lines.join('\n'));
  }
  function convert() {
    try {
      const parsed = JSON.parse(input);
      const structs = new Map<string, string>();
      
      if (Array.isArray(parsed)) {
        if (parsed.length > 0 && typeof parsed[0] === 'object') {
          generateStruct(parsed[0] as Record<string, unknown>, structName, structs);
        }
      } else if (typeof parsed === 'object' && parsed !== null) {
        generateStruct(parsed as Record<string, unknown>, structName, structs);
      }
      
      const result = Array.from(structs.values()).reverse().join('\n\n');
      output = result;
    } catch {
      output = t('errorInvalidJson');
    }
  }
  function copyToClipboard() {
    navigator.clipboard.writeText(output);
  }

</script>


    <div class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('structName')}</label>
          <input type="text" bind:value={structName}
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white" />
        </div>
        <div class="flex items-center gap-4">
          <label class="flex items-center gap-2 text-gray-600 dark:text-gray-300">
            <input type="checkbox" bind:checked={useCodable}
              class="rounded bg-gray-200 dark:bg-gray-700 border-gray-300 dark:border-gray-600" />
            {t('useCodable')}
          </label>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div>
          <label class="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('input')}</label>
          <textarea bind:value={input}
            class="w-full h-80 px-4 py-3 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white font-mono text-sm"
            placeholder={t('inputPlaceholder')}></textarea>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-600 dark:text-gray-300 mb-2">{t('output')}</label>
          <textarea value={output} readOnly
            class="w-full h-80 px-4 py-3 bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-900 dark:text-white font-mono text-sm"
            placeholder={t('outputPlaceholder')}></textarea>
        </div>
      </div>

      <div class="flex gap-4">
        <button onclick={convert}
          class="px-6 py-2 bg-orange-600 hover:bg-orange-700 text-white rounded-lg font-medium transition-colors">
          {t('convert')}
        </button>
        <button onclick={copyToClipboard} disabled={!output}
          class="px-6 py-2 bg-gray-200 dark:bg-gray-600 hover:bg-gray-300 dark:hover:bg-gray-500 text-gray-900 dark:text-white disabled:opacity-50 rounded-lg font-medium transition-colors">
          {t('copy')}
        </button>
      </div>
    </div>
