// src/components/tools/MetricImperialConverter.svelte
<script lang="ts">
  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  let { locale, translations }: Props = $props();

  // Translation helpers
  function t(key: string): string {
    const scope = translations['tools']['metric-imperial-converter'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.metric-imperial-converter.${key}`;
  }

  // Types
  type ConversionCategory = 'length' | 'weight' | 'volume' | 'temperature' | 'area' | 'speed';
  interface ConversionUnit {
    name: string;
    toBase: (value: number) => number;
    fromBase: (value: number) => number;
    symbol: string;
    system: 'metric' | 'imperial';
  }

  const categoryIcons: Record<ConversionCategory, string> = {
    length: '📏',
    weight: '⚖️',
    volume: '🧪',
    temperature: '🌡️',
    area: '▦',
    speed: '⚡',
  };

  const conversions: Record<ConversionCategory, Record<string, ConversionUnit>> = {
    length: {
      meter: { name: 'Meter', symbol: 'm', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      kilometer: { name: 'Kilometer', symbol: 'km', system: 'metric', toBase: (value) => value * 1000, fromBase: (value) => value / 1000 },
      centimeter: { name: 'Centimeter', symbol: 'cm', system: 'metric', toBase: (value) => value / 100, fromBase: (value) => value * 100 },
      inch: { name: 'Inch', symbol: 'in', system: 'imperial', toBase: (value) => value * 0.0254, fromBase: (value) => value / 0.0254 },
      foot: { name: 'Foot', symbol: 'ft', system: 'imperial', toBase: (value) => value * 0.3048, fromBase: (value) => value / 0.3048 },
      yard: { name: 'Yard', symbol: 'yd', system: 'imperial', toBase: (value) => value * 0.9144, fromBase: (value) => value / 0.9144 },
      mile: { name: 'Mile', symbol: 'mi', system: 'imperial', toBase: (value) => value * 1609.344, fromBase: (value) => value / 1609.344 },
    },
    weight: {
      kilogram: { name: 'Kilogram', symbol: 'kg', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      gram: { name: 'Gram', symbol: 'g', system: 'metric', toBase: (value) => value / 1000, fromBase: (value) => value * 1000 },
      tonne: { name: 'Tonne', symbol: 't', system: 'metric', toBase: (value) => value * 1000, fromBase: (value) => value / 1000 },
      ounce: { name: 'Ounce', symbol: 'oz', system: 'imperial', toBase: (value) => value * 0.028349523125, fromBase: (value) => value / 0.028349523125 },
      pound: { name: 'Pound', symbol: 'lb', system: 'imperial', toBase: (value) => value * 0.45359237, fromBase: (value) => value / 0.45359237 },
      stone: { name: 'Stone', symbol: 'st', system: 'imperial', toBase: (value) => value * 6.35029318, fromBase: (value) => value / 6.35029318 },
    },
    volume: {
      liter: { name: 'Liter', symbol: 'L', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      milliliter: { name: 'Milliliter', symbol: 'mL', system: 'metric', toBase: (value) => value / 1000, fromBase: (value) => value * 1000 },
      cubicMeter: { name: 'Cubic meter', symbol: 'm³', system: 'metric', toBase: (value) => value * 1000, fromBase: (value) => value / 1000 },
      fluidOunce: { name: 'Fluid ounce', symbol: 'fl oz', system: 'imperial', toBase: (value) => value * 0.0295735295625, fromBase: (value) => value / 0.0295735295625 },
      pint: { name: 'Pint', symbol: 'pt', system: 'imperial', toBase: (value) => value * 0.473176473, fromBase: (value) => value / 0.473176473 },
      gallon: { name: 'Gallon', symbol: 'gal', system: 'imperial', toBase: (value) => value * 3.785411784, fromBase: (value) => value / 3.785411784 },
    },
    temperature: {
      celsius: { name: 'Celsius', symbol: '°C', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      kelvin: { name: 'Kelvin', symbol: 'K', system: 'metric', toBase: (value) => value - 273.15, fromBase: (value) => value + 273.15 },
      fahrenheit: { name: 'Fahrenheit', symbol: '°F', system: 'imperial', toBase: (value) => (value - 32) * 5 / 9, fromBase: (value) => value * 9 / 5 + 32 },
      rankine: { name: 'Rankine', symbol: '°R', system: 'imperial', toBase: (value) => (value - 491.67) * 5 / 9, fromBase: (value) => (value + 273.15) * 9 / 5 },
    },
    area: {
      squareMeter: { name: 'Square meter', symbol: 'm²', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      squareKilometer: { name: 'Square kilometer', symbol: 'km²', system: 'metric', toBase: (value) => value * 1_000_000, fromBase: (value) => value / 1_000_000 },
      hectare: { name: 'Hectare', symbol: 'ha', system: 'metric', toBase: (value) => value * 10_000, fromBase: (value) => value / 10_000 },
      squareFoot: { name: 'Square foot', symbol: 'ft²', system: 'imperial', toBase: (value) => value * 0.09290304, fromBase: (value) => value / 0.09290304 },
      squareYard: { name: 'Square yard', symbol: 'yd²', system: 'imperial', toBase: (value) => value * 0.83612736, fromBase: (value) => value / 0.83612736 },
      acre: { name: 'Acre', symbol: 'ac', system: 'imperial', toBase: (value) => value * 4046.8564224, fromBase: (value) => value / 4046.8564224 },
    },
    speed: {
      meterPerSecond: { name: 'Meter per second', symbol: 'm/s', system: 'metric', toBase: (value) => value, fromBase: (value) => value },
      kilometerPerHour: { name: 'Kilometer per hour', symbol: 'km/h', system: 'metric', toBase: (value) => value / 3.6, fromBase: (value) => value * 3.6 },
      footPerSecond: { name: 'Foot per second', symbol: 'ft/s', system: 'imperial', toBase: (value) => value * 0.3048, fromBase: (value) => value / 0.3048 },
      milePerHour: { name: 'Mile per hour', symbol: 'mph', system: 'imperial', toBase: (value) => value * 0.44704, fromBase: (value) => value / 0.44704 },
      knot: { name: 'Knot', symbol: 'kn', system: 'imperial', toBase: (value) => value * 0.514444, fromBase: (value) => value / 0.514444 },
    },
  };

  let category = $state<ConversionCategory>('length');

  let fromUnit = $state('meter');

  let toUnit = $state('foot');

  let inputValue = $state('1');

  let result = $state<number | null>(null);

  const categoryUnits = $derived(conversions[category]);
  const metricUnits = $derived(Object.entries(categoryUnits).filter(([, unit]) => unit.system === 'metric'));
  const imperialUnits = $derived(Object.entries(categoryUnits).filter(([, unit]) => unit.system === 'imperial'));

  $effect(() => {
    if (categoryUnits[fromUnit] && categoryUnits[toUnit]) {
      return;
    }

    const units = Object.keys(categoryUnits);
    const metricUnit = units.find(unit => categoryUnits[unit].system === 'metric') || units[0];
    const imperialUnit = units.find(unit => categoryUnits[unit].system === 'imperial') || units[1] || metricUnit;
    fromUnit = metricUnit;
    toUnit = imperialUnit;
  });

  $effect(() => {
    convert();
  });

  // Functions
  function convert() {
    const value = parseFloat(inputValue);
    if (isNaN(value)) {
      result = null;
      return;
    }

    const fromConversion = categoryUnits[fromUnit];
    const toConversion = categoryUnits[toUnit];

    if (!fromConversion || !toConversion) {
      result = null;
      return;
    }

    const baseValue = fromConversion.toBase(value);
    const convertedValue = toConversion.fromBase(baseValue);
    result = convertedValue;
  }
  function handleSwap() {
    const previousFromUnit = fromUnit;
    fromUnit = toUnit;
    toUnit = previousFromUnit;
    if (result !== null) {
      inputValue = result.toString();
    }
  }
  function formatResult(value: number): string {
    if (Math.abs(value) < 0.0001 || Math.abs(value) >= 1000000) {
      return value.toExponential(6);
    }
    return value.toLocaleString('en-US', { maximumFractionDigits: 6 });
  }
</script>


    <div class="space-y-6">
      <!-- Category Selection -->
      <div class="grid grid-cols-3 md:grid-cols-6 gap-2">
        {#each (Object.keys(conversions) as ConversionCategory[]) as cat (cat)}
<button 
            onclick={() => category = cat}
            class={`p-3 rounded-lg border transition-colors text-center ${
              category === cat
                ? 'bg-amber-600 text-white border-amber-600'
                : 'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
            }`}
          >
            <div class="text-2xl mb-1">{categoryIcons[cat]}</div>
            <div class="text-xs font-medium">{t(`categories.${cat}`)}</div>
          </button>
{/each}
      </div>

      <!-- Converter -->
      <div class="grid grid-cols-1 md:grid-cols-[1fr,auto,1fr] gap-4 items-end">
        <div>
          <label class="tool-label">
            {t('from')}
          </label>
          <input
            type="number"
            bind:value={inputValue}
            class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-lg mb-2"
            placeholder="1"
          />
          <select
            bind:value={fromUnit}
            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            <optgroup label={t('metric')}>
              {#each metricUnits as [key, unit] (key)}
<option  value={key}>{unit.name} ({unit.symbol})</option>
{/each}
            </optgroup>
            <optgroup label={t('imperial')}>
              {#each imperialUnits as [key, unit] (key)}
<option  value={key}>{unit.name} ({unit.symbol})</option>
{/each}
            </optgroup>
          </select>
        </div>

        <button
          onclick={handleSwap}
          class="p-3 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors self-center mb-6"
          title={t('swap')}
        >
          <svg class="w-6 h-6 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"></path>
          </svg>
        </button>

        <div>
          <label class="tool-label">
            {t('to')}
          </label>
          <div class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white text-lg mb-2 min-h-[52px] flex items-center">
            {result !== null ? formatResult(result) : '-'}
          </div>
          <select
            bind:value={toUnit}
            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            <optgroup label={t('metric')}>
              {#each metricUnits as [key, unit] (key)}
<option  value={key}>{unit.name} ({unit.symbol})</option>
{/each}
            </optgroup>
            <optgroup label={t('imperial')}>
              {#each imperialUnits as [key, unit] (key)}
<option  value={key}>{unit.name} ({unit.symbol})</option>
{/each}
            </optgroup>
          </select>
        </div>
      </div>

      <!-- Result Display -->
      {#if result !== null}
<div class="p-6 bg-gradient-to-r from-amber-50 to-slate-50 dark:from-amber-900/20 dark:to-slate-900/20 rounded-xl text-center">
          <div class="text-lg text-gray-600 dark:text-gray-400 mb-2">
            {inputValue} {categoryUnits[fromUnit]?.symbol} =
          </div>
          <div class="text-3xl font-bold text-amber-600 dark:text-amber-400">
            {formatResult(result)} {categoryUnits[toUnit]?.symbol}
          </div>
        </div>
{/if}

      <!-- Quick Reference -->
      <div>
        <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-3">
          {t('quickReference')}
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="p-4 bg-amber-50 dark:bg-amber-900/20 rounded-lg">
            <h4 class="font-medium text-amber-800 dark:text-amber-300 mb-2">{t('metric')}</h4>
            <ul class="text-sm text-gray-600 dark:text-gray-400 space-y-1">
              {#each metricUnits as [key, unit] (key)}
<li >{unit.name} ({unit.symbol})</li>
{/each}
            </ul>
          </div>
          <div class="p-4 bg-orange-50 dark:bg-orange-900/20 rounded-lg">
            <h4 class="font-medium text-orange-800 dark:text-orange-300 mb-2">{t('imperial')}</h4>
            <ul class="text-sm text-gray-600 dark:text-gray-400 space-y-1">
              {#each imperialUnits as [key, unit] (key)}
<li >{unit.name} ({unit.symbol})</li>
{/each}
            </ul>
          </div>
        </div>
      </div>
    </div>

// src/components/tools/MetricImperialConverter.tsx
'use client';

import { useState, useEffect } from 'react';
import { useTranslations } from 'next-intl';

type ConversionCategory = 'length' | 'weight' | 'volume' | 'temperature' | 'area' | 'speed';

interface ConversionUnit {
  name: string;
  toBase: (value: number) => number;
  fromBase: (value: number) => number;
  symbol: string;
  system: 'metric' | 'imperial';
}

const conversions: Record<ConversionCategory, Record<string, ConversionUnit>> = {
  length: {
    meter: { name: 'Meter', symbol: 'm', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    kilometer: { name: 'Kilometer', symbol: 'km', system: 'metric', toBase: (v) => v * 1000, fromBase: (v) => v / 1000 },
    centimeter: { name: 'Centimeter', symbol: 'cm', system: 'metric', toBase: (v) => v / 100, fromBase: (v) => v * 100 },
    millimeter: { name: 'Millimeter', symbol: 'mm', system: 'metric', toBase: (v) => v / 1000, fromBase: (v) => v * 1000 },
    inch: { name: 'Inch', symbol: 'in', system: 'imperial', toBase: (v) => v * 0.0254, fromBase: (v) => v / 0.0254 },
    foot: { name: 'Foot', symbol: 'ft', system: 'imperial', toBase: (v) => v * 0.3048, fromBase: (v) => v / 0.3048 },
    yard: { name: 'Yard', symbol: 'yd', system: 'imperial', toBase: (v) => v * 0.9144, fromBase: (v) => v / 0.9144 },
    mile: { name: 'Mile', symbol: 'mi', system: 'imperial', toBase: (v) => v * 1609.344, fromBase: (v) => v / 1609.344 },
  },
  weight: {
    kilogram: { name: 'Kilogram', symbol: 'kg', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    gram: { name: 'Gram', symbol: 'g', system: 'metric', toBase: (v) => v / 1000, fromBase: (v) => v * 1000 },
    milligram: { name: 'Milligram', symbol: 'mg', system: 'metric', toBase: (v) => v / 1000000, fromBase: (v) => v * 1000000 },
    tonne: { name: 'Tonne', symbol: 't', system: 'metric', toBase: (v) => v * 1000, fromBase: (v) => v / 1000 },
    pound: { name: 'Pound', symbol: 'lb', system: 'imperial', toBase: (v) => v * 0.453592, fromBase: (v) => v / 0.453592 },
    ounce: { name: 'Ounce', symbol: 'oz', system: 'imperial', toBase: (v) => v * 0.0283495, fromBase: (v) => v / 0.0283495 },
    stone: { name: 'Stone', symbol: 'st', system: 'imperial', toBase: (v) => v * 6.35029, fromBase: (v) => v / 6.35029 },
  },
  volume: {
    liter: { name: 'Liter', symbol: 'L', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    milliliter: { name: 'Milliliter', symbol: 'mL', system: 'metric', toBase: (v) => v / 1000, fromBase: (v) => v * 1000 },
    cubicMeter: { name: 'Cubic Meter', symbol: 'm³', system: 'metric', toBase: (v) => v * 1000, fromBase: (v) => v / 1000 },
    gallon: { name: 'Gallon (US)', symbol: 'gal', system: 'imperial', toBase: (v) => v * 3.78541, fromBase: (v) => v / 3.78541 },
    gallonUK: { name: 'Gallon (UK)', symbol: 'gal UK', system: 'imperial', toBase: (v) => v * 4.54609, fromBase: (v) => v / 4.54609 },
    quart: { name: 'Quart', symbol: 'qt', system: 'imperial', toBase: (v) => v * 0.946353, fromBase: (v) => v / 0.946353 },
    pint: { name: 'Pint', symbol: 'pt', system: 'imperial', toBase: (v) => v * 0.473176, fromBase: (v) => v / 0.473176 },
    fluidOunce: { name: 'Fluid Ounce', symbol: 'fl oz', system: 'imperial', toBase: (v) => v * 0.0295735, fromBase: (v) => v / 0.0295735 },
  },
  temperature: {
    celsius: { name: 'Celsius', symbol: '°C', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    fahrenheit: { name: 'Fahrenheit', symbol: '°F', system: 'imperial', toBase: (v) => (v - 32) * 5/9, fromBase: (v) => v * 9/5 + 32 },
    kelvin: { name: 'Kelvin', symbol: 'K', system: 'metric', toBase: (v) => v - 273.15, fromBase: (v) => v + 273.15 },
  },
  area: {
    squareMeter: { name: 'Square Meter', symbol: 'm²', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    squareKilometer: { name: 'Square Kilometer', symbol: 'km²', system: 'metric', toBase: (v) => v * 1000000, fromBase: (v) => v / 1000000 },
    hectare: { name: 'Hectare', symbol: 'ha', system: 'metric', toBase: (v) => v * 10000, fromBase: (v) => v / 10000 },
    squareFoot: { name: 'Square Foot', symbol: 'ft²', system: 'imperial', toBase: (v) => v * 0.092903, fromBase: (v) => v / 0.092903 },
    squareYard: { name: 'Square Yard', symbol: 'yd²', system: 'imperial', toBase: (v) => v * 0.836127, fromBase: (v) => v / 0.836127 },
    acre: { name: 'Acre', symbol: 'ac', system: 'imperial', toBase: (v) => v * 4046.86, fromBase: (v) => v / 4046.86 },
    squareMile: { name: 'Square Mile', symbol: 'mi²', system: 'imperial', toBase: (v) => v * 2589988, fromBase: (v) => v / 2589988 },
  },
  speed: {
    meterPerSecond: { name: 'Meter/Second', symbol: 'm/s', system: 'metric', toBase: (v) => v, fromBase: (v) => v },
    kilometerPerHour: { name: 'Kilometer/Hour', symbol: 'km/h', system: 'metric', toBase: (v) => v / 3.6, fromBase: (v) => v * 3.6 },
    milePerHour: { name: 'Mile/Hour', symbol: 'mph', system: 'imperial', toBase: (v) => v * 0.44704, fromBase: (v) => v / 0.44704 },
    footPerSecond: { name: 'Foot/Second', symbol: 'ft/s', system: 'imperial', toBase: (v) => v * 0.3048, fromBase: (v) => v / 0.3048 },
    knot: { name: 'Knot', symbol: 'kn', system: 'imperial', toBase: (v) => v * 0.514444, fromBase: (v) => v / 0.514444 },
  },
};

const categoryIcons: Record<ConversionCategory, string> = {
  length: '📏',
  weight: '⚖️',
  volume: '🧪',
  temperature: '🌡️',
  area: '📐',
  speed: '🚀',
};

export default function MetricImperialConverter() {
  const t = useTranslations('tools.metric-imperial-converter');

  const [category, setCategory] = useState<ConversionCategory>('length');
  const [fromUnit, setFromUnit] = useState<string>('meter');
  const [toUnit, setToUnit] = useState<string>('foot');
  const [inputValue, setInputValue] = useState<string>('1');
  const [result, setResult] = useState<number | null>(null);

  useEffect(() => {
    const units = Object.keys(conversions[category]);
    const metricUnit = units.find(u => conversions[category][u].system === 'metric') || units[0];
    const imperialUnit = units.find(u => conversions[category][u].system === 'imperial') || units[1];
    setFromUnit(metricUnit);
    setToUnit(imperialUnit);
  }, [category]);

  useEffect(() => {
    convert();
  }, [inputValue, fromUnit, toUnit, category]);

  const convert = () => {
    const value = parseFloat(inputValue);
    if (isNaN(value)) {
      setResult(null);
      return;
    }

    const fromConversion = conversions[category][fromUnit];
    const toConversion = conversions[category][toUnit];

    if (!fromConversion || !toConversion) {
      setResult(null);
      return;
    }

    const baseValue = fromConversion.toBase(value);
    const convertedValue = toConversion.fromBase(baseValue);
    setResult(convertedValue);
  };

  const handleSwap = () => {
    setFromUnit(toUnit);
    setToUnit(fromUnit);
    if (result !== null) {
      setInputValue(result.toString());
    }
  };

  const formatResult = (value: number): string => {
    if (Math.abs(value) < 0.0001 || Math.abs(value) >= 1000000) {
      return value.toExponential(6);
    }
    return value.toLocaleString('en-US', { maximumFractionDigits: 6 });
  };

  const categoryUnits = conversions[category];
  const metricUnits = Object.entries(categoryUnits).filter(([, u]) => u.system === 'metric');
  const imperialUnits = Object.entries(categoryUnits).filter(([, u]) => u.system === 'imperial');

  return (
    <div className="space-y-6">
      {/* Category Selection */}
      <div className="grid grid-cols-3 md:grid-cols-6 gap-2">
        {(Object.keys(conversions) as ConversionCategory[]).map((cat) => (
          <button
            key={cat}
            onClick={() => setCategory(cat)}
            className={`p-3 rounded-lg border transition-colors text-center ${
              category === cat
                ? 'bg-blue-600 text-white border-blue-600'
                : 'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
            }`}
          >
            <div className="text-2xl mb-1">{categoryIcons[cat]}</div>
            <div className="text-xs font-medium">{t(`categories.${cat}`)}</div>
          </button>
        ))}
      </div>

      {/* Converter */}
      <div className="grid grid-cols-1 md:grid-cols-[1fr,auto,1fr] gap-4 items-end">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('from')}
          </label>
          <input
            type="number"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-lg mb-2"
            placeholder="1"
          />
          <select
            value={fromUnit}
            onChange={(e) => setFromUnit(e.target.value)}
            className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            <optgroup label={t('metric')}>
              {metricUnits.map(([key, unit]) => (
                <option key={key} value={key}>{unit.name} ({unit.symbol})</option>
              ))}
            </optgroup>
            <optgroup label={t('imperial')}>
              {imperialUnits.map(([key, unit]) => (
                <option key={key} value={key}>{unit.name} ({unit.symbol})</option>
              ))}
            </optgroup>
          </select>
        </div>

        <button
          onClick={handleSwap}
          className="p-3 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors self-center mb-6"
          title={t('swap')}
        >
          <svg className="w-6 h-6 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
          </svg>
        </button>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('to')}
          </label>
          <div className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white text-lg mb-2 min-h-[52px] flex items-center">
            {result !== null ? formatResult(result) : '-'}
          </div>
          <select
            value={toUnit}
            onChange={(e) => setToUnit(e.target.value)}
            className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
          >
            <optgroup label={t('metric')}>
              {metricUnits.map(([key, unit]) => (
                <option key={key} value={key}>{unit.name} ({unit.symbol})</option>
              ))}
            </optgroup>
            <optgroup label={t('imperial')}>
              {imperialUnits.map(([key, unit]) => (
                <option key={key} value={key}>{unit.name} ({unit.symbol})</option>
              ))}
            </optgroup>
          </select>
        </div>
      </div>

      {/* Result Display */}
      {result !== null && (
        <div className="p-6 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl text-center">
          <div className="text-lg text-gray-600 dark:text-gray-400 mb-2">
            {inputValue} {categoryUnits[fromUnit]?.symbol} =
          </div>
          <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">
            {formatResult(result)} {categoryUnits[toUnit]?.symbol}
          </div>
        </div>
      )}

      {/* Quick Reference */}
      <div>
        <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-3">
          {t('quickReference')}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
            <h4 className="font-medium text-blue-800 dark:text-blue-300 mb-2">{t('metric')}</h4>
            <ul className="text-sm text-gray-600 dark:text-gray-400 space-y-1">
              {metricUnits.map(([key, unit]) => (
                <li key={key}>{unit.name} ({unit.symbol})</li>
              ))}
            </ul>
          </div>
          <div className="p-4 bg-orange-50 dark:bg-orange-900/20 rounded-lg">
            <h4 className="font-medium text-orange-800 dark:text-orange-300 mb-2">{t('imperial')}</h4>
            <ul className="text-sm text-gray-600 dark:text-gray-400 space-y-1">
              {imperialUnits.map(([key, unit]) => (
                <li key={key}>{unit.name} ({unit.symbol})</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
