// src/components/tools/VatCalculator.tsx
'use client';

import { useState, useEffect } from 'react';
import { useTranslations } from 'next-intl';

// EU VAT rates (standard rates as of 2024)
const vatRates: Record<string, { name: string; standard: number; reduced: number[]; superReduced?: number }> = {
  AT: { name: 'Austria', standard: 20, reduced: [10, 13] },
  BE: { name: 'Belgium', standard: 21, reduced: [6, 12] },
  BG: { name: 'Bulgaria', standard: 20, reduced: [9] },
  HR: { name: 'Croatia', standard: 25, reduced: [5, 13] },
  CY: { name: 'Cyprus', standard: 19, reduced: [5, 9] },
  CZ: { name: 'Czech Republic', standard: 21, reduced: [12, 15] },
  DK: { name: 'Denmark', standard: 25, reduced: [] },
  EE: { name: 'Estonia', standard: 22, reduced: [9] },
  FI: { name: 'Finland', standard: 24, reduced: [10, 14] },
  FR: { name: 'France', standard: 20, reduced: [5.5, 10], superReduced: 2.1 },
  DE: { name: 'Germany', standard: 19, reduced: [7] },
  GR: { name: 'Greece', standard: 24, reduced: [6, 13] },
  HU: { name: 'Hungary', standard: 27, reduced: [5, 18] },
  IE: { name: 'Ireland', standard: 23, reduced: [9, 13.5], superReduced: 4.8 },
  IT: { name: 'Italy', standard: 22, reduced: [5, 10], superReduced: 4 },
  LV: { name: 'Latvia', standard: 21, reduced: [5, 12] },
  LT: { name: 'Lithuania', standard: 21, reduced: [5, 9] },
  LU: { name: 'Luxembourg', standard: 17, reduced: [8], superReduced: 3 },
  MT: { name: 'Malta', standard: 18, reduced: [5, 7] },
  NL: { name: 'Netherlands', standard: 21, reduced: [9] },
  PL: { name: 'Poland', standard: 23, reduced: [5, 8] },
  PT: { name: 'Portugal', standard: 23, reduced: [6, 13] },
  RO: { name: 'Romania', standard: 19, reduced: [5, 9] },
  SK: { name: 'Slovakia', standard: 20, reduced: [10] },
  SI: { name: 'Slovenia', standard: 22, reduced: [5, 9.5] },
  ES: { name: 'Spain', standard: 21, reduced: [10], superReduced: 4 },
  SE: { name: 'Sweden', standard: 25, reduced: [6, 12] },
  CH: { name: 'Switzerland', standard: 8.1, reduced: [2.6, 3.8] },
  GB: { name: 'United Kingdom', standard: 20, reduced: [5] },
  NO: { name: 'Norway', standard: 25, reduced: [12, 15] },
};

type CalculationMode = 'addVat' | 'removeVat' | 'vatOnly';

export default function VatCalculator() {
  const t = useTranslations('tools.vat-calculator');

  const [amount, setAmount] = useState<string>('100');
  const [country, setCountry] = useState<string>('DE');
  const [customRate, setCustomRate] = useState<string>('');
  const [useCustomRate, setUseCustomRate] = useState(false);
  const [mode, setMode] = useState<CalculationMode>('addVat');
  const [selectedRateType, setSelectedRateType] = useState<'standard' | 'reduced' | 'superReduced'>('standard');
  const [reducedIndex, setReducedIndex] = useState(0);

  const [result, setResult] = useState<{
    netAmount: number;
    vatAmount: number;
    grossAmount: number;
    vatRate: number;
  } | null>(null);

  const getVatRate = (): number => {
    if (useCustomRate) {
      return parseFloat(customRate) || 0;
    }
    const countryData = vatRates[country];
    if (!countryData) return 0;

    if (selectedRateType === 'standard') return countryData.standard;
    if (selectedRateType === 'superReduced' && countryData.superReduced) return countryData.superReduced;
    if (selectedRateType === 'reduced' && countryData.reduced.length > 0) {
      return countryData.reduced[reducedIndex] || countryData.reduced[0];
    }
    return countryData.standard;
  };

  useEffect(() => {
    calculate();
  }, [amount, country, customRate, useCustomRate, mode, selectedRateType, reducedIndex]);

  const calculate = () => {
    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount < 0) {
      setResult(null);
      return;
    }

    const vatRate = getVatRate();
    const vatMultiplier = vatRate / 100;

    let netAmount: number;
    let vatAmount: number;
    let grossAmount: number;

    switch (mode) {
      case 'addVat':
        netAmount = numAmount;
        vatAmount = numAmount * vatMultiplier;
        grossAmount = numAmount + vatAmount;
        break;
      case 'removeVat':
        grossAmount = numAmount;
        netAmount = numAmount / (1 + vatMultiplier);
        vatAmount = grossAmount - netAmount;
        break;
      case 'vatOnly':
        netAmount = numAmount;
        vatAmount = numAmount * vatMultiplier;
        grossAmount = numAmount + vatAmount;
        break;
      default:
        return;
    }

    setResult({ netAmount, vatAmount, grossAmount, vatRate });
  };

  const countryData = vatRates[country];

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('amount')}
          </label>
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">€</span>
            <input
              type="number"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              className="tool-input pl-8 text-lg"
              placeholder="100.00"
              min="0"
              step="0.01"
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('calculationMode')}
          </label>
          <select
            value={mode}
            onChange={(e) => setMode(e.target.value as CalculationMode)}
            className="tool-select"
          >
            <option value="addVat">{t('addVat')}</option>
            <option value="removeVat">{t('removeVat')}</option>
            <option value="vatOnly">{t('vatOnly')}</option>
          </select>
        </div>
      </div>

      <div className="tool-card space-y-4">
        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={useCustomRate}
              onChange={(e) => setUseCustomRate(e.target.checked)}
              className="w-4 h-4 rounded"
            />
            <span className="text-sm text-gray-700 dark:text-gray-300">{t('useCustomRate')}</span>
          </label>
        </div>

        {useCustomRate ? (
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('customRate')}
            </label>
            <div className="relative w-48">
              <input
                type="number"
                value={customRate}
                onChange={(e) => setCustomRate(e.target.value)}
                className="tool-input pr-8"
                placeholder="19"
                min="0"
                max="100"
                step="0.1"
              />
              <span className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500">%</span>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('country')}
              </label>
              <select
                value={country}
                onChange={(e) => {
                  setCountry(e.target.value);
                  setSelectedRateType('standard');
                  setReducedIndex(0);
                }}
                className="tool-select"
              >
                {Object.entries(vatRates).map(([code, data]) => (
                  <option key={code} value={code}>
                    {data.name} ({data.standard}%)
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('rateType')}
              </label>
              <select
                value={selectedRateType === 'reduced' ? `reduced-${reducedIndex}` : selectedRateType}
                onChange={(e) => {
                  const value = e.target.value;
                  if (value.startsWith('reduced-')) {
                    setSelectedRateType('reduced');
                    setReducedIndex(parseInt(value.split('-')[1]));
                  } else {
                    setSelectedRateType(value as 'standard' | 'superReduced');
                  }
                }}
                className="tool-select"
              >
                <option value="standard">
                  {t('standardRate')} ({countryData?.standard}%)
                </option>
                {countryData?.reduced.map((rate, index) => (
                  <option key={index} value={`reduced-${index}`}>
                    {t('reducedRate')} ({rate}%)
                  </option>
                ))}
                {countryData?.superReduced && (
                  <option value="superReduced">
                    {t('superReducedRate')} ({countryData.superReduced}%)
                  </option>
                )}
              </select>
            </div>
          </div>
        )}
      </div>

      {result && (
        <div className="p-6 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl border border-blue-100 dark:border-blue-800/30">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div className="text-sm text-gray-500 dark:text-gray-400">{t('netAmount')}</div>
              <div className="text-2xl font-bold text-gray-900 dark:text-white">
                €{result.netAmount.toFixed(2)}
              </div>
            </div>
            <div className="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div className="text-sm text-gray-500 dark:text-gray-400">
                {t('vatAmount')} ({result.vatRate}%)
              </div>
              <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                €{result.vatAmount.toFixed(2)}
              </div>
            </div>
            <div className="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div className="text-sm text-gray-500 dark:text-gray-400">{t('grossAmount')}</div>
              <div className="text-2xl font-bold text-green-600 dark:text-green-400">
                €{result.grossAmount.toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      )}

      <div>
        <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-3">
          {t('euVatRates')}
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-100 dark:bg-gray-700">
                <th className="px-3 py-2 text-left">{t('country')}</th>
                <th className="px-3 py-2 text-center">{t('standardRate')}</th>
                <th className="px-3 py-2 text-center">{t('reducedRates')}</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(vatRates).slice(0, 10).map(([code, data]) => (
                <tr key={code} className="border-b dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800">
                  <td className="px-3 py-2">{data.name}</td>
                  <td className="px-3 py-2 text-center font-medium">{data.standard}%</td>
                  <td className="px-3 py-2 text-center text-gray-500">
                    {data.reduced.length > 0 ? data.reduced.join('%, ') + '%' : '-'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// src/components/tools/VatCalculator.svelte
<script lang="ts">
  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  let { locale, translations }: Props = $props();

  // Translation helpers
  function t(key: string): string {
    const scope = translations['tools']['vat-calculator'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.vat-calculator.${key}`;
  }

  // Types
  type CalculationMode = 'addVat' | 'removeVat' | 'vatOnly';

  let amount = $state('100');

  let country = $state('DE');

  let customRate = $state('');

  let useCustomRate = $state(false);

  let mode = $state('addVat');

  let selectedRateType = $state('standard');

  let reducedIndex = $state(0);

  let result = $state(null);

  $effect(() => {
    calculate();
  });

  // Functions
  function getVatRate(): number {
    if (useCustomRate) {
      return parseFloat(customRate) || 0;
    }
    const countryData = vatRates[country];
    if (!countryData) return 0;

    if (selectedRateType === 'standard') return countryData.standard;
    if (selectedRateType === 'superReduced' && countryData.superReduced) return countryData.superReduced;
    if (selectedRateType === 'reduced' && countryData.reduced.length > 0) {
      return countryData.reduced[reducedIndex] || countryData.reduced[0];
    }
    return countryData.standard;
  }
  function calculate() {
    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount < 0) {
      result = null;
      return;
    }

    const vatRate = getVatRate();
    const vatMultiplier = vatRate / 100;

    let netAmount: number;
    let vatAmount: number;
    let grossAmount: number;

    switch (mode) {
      case 'addVat':
        netAmount = numAmount;
        vatAmount = numAmount * vatMultiplier;
        grossAmount = numAmount + vatAmount;
        break;
      case 'removeVat':
        grossAmount = numAmount;
        netAmount = numAmount / (1 + vatMultiplier);
        vatAmount = grossAmount - netAmount;
        break;
      case 'vatOnly':
        netAmount = numAmount;
        vatAmount = numAmount * vatMultiplier;
        grossAmount = numAmount + vatAmount;
        break;
      default:
        return;
    }

    result = { netAmount, vatAmount, grossAmount, vatRate };
  }
  const countryData = vatRates[country];

</script>


    <div class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('amount')}
          </label>
          <div class="relative">
            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">€</span>
            <input
              type="number"
              bind:value={amount}
              class="tool-input pl-8 text-lg"
              placeholder="100.00"
              min="0"
              step="0.01"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('calculationMode')}
          </label>
          <select
            value={mode}
            onchange={(e) => mode = e.target.value as CalculationMode}
            class="tool-select"
          >
            <option value="addVat">{t('addVat')}</option>
            <option value="removeVat">{t('removeVat')}</option>
            <option value="vatOnly">{t('vatOnly')}</option>
          </select>
        </div>
      </div>

      <div class="tool-card space-y-4">
        <div class="flex items-center gap-4">
          <label class="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              bind:checked={useCustomRate}
              class="w-4 h-4 rounded"
            />
            <span class="text-sm text-gray-700 dark:text-gray-300">{t('useCustomRate')}</span>
          </label>
        </div>

        {#if useCustomRate}
<div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('customRate')}
            </label>
            <div class="relative w-48">
              <input
                type="number"
                bind:value={customRate}
                class="tool-input pr-8"
                placeholder="19"
                min="0"
                max="100"
                step="0.1"
              />
              <span class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500">%</span>
            </div>
          </div>
{:else}
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('country')}
              </label>
              <select
                value={country}
                onchange={(e) => {
                  country = e.target.value;
                  selectedRateType = 'standard';
                  reducedIndex = 0;
                }}
                class="tool-select"
              >
                {#each Object.entries(vatRates) as [code, data] (code)}
<option  value={code}>
                    {data.name} ({data.standard}%)
                  </option>
{/each}
              </select>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('rateType')}
              </label>
              <select
                value={selectedRateType === 'reduced' ? `reduced-${reducedIndex}` : selectedRateType}
                onchange={(e) => {
                  const value = e.target.value;
                  if (value.startsWith('reduced-')) {
                    selectedRateType = 'reduced';
                    reducedIndex = parseInt(value.split('-')[1]);
                  } else {
                    selectedRateType = value as 'standard' | 'superReduced';
                  }
                }}
                class="tool-select"
              >
                <option value="standard">
                  {t('standardRate')} ({countryData?.standard}%)
                </option>
                {#each countryData?.reduced as rate, index (index)}
<option  value={`reduced-${index}`}>
                    {t('reducedRate')} ({rate}%)
                  </option>
{/each}
                {#if countryData?.superReduced}
<option value="superReduced">
                    {t('superReducedRate')} ({countryData.superReduced}%)
                  </option>
{/if}
              </select>
            </div>
          </div>
{/if}
      </div>

      {#if result}
<div class="p-6 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl border border-blue-100 dark:border-blue-800/30">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div class="text-sm text-gray-500 dark:text-gray-400">{t('netAmount')}</div>
              <div class="text-2xl font-bold text-gray-900 dark:text-white">
                €{result.netAmount.toFixed(2)}
              </div>
            </div>
            <div class="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div class="text-sm text-gray-500 dark:text-gray-400">
                {t('vatAmount')} ({result.vatRate}%)
              </div>
              <div class="text-2xl font-bold text-blue-600 dark:text-blue-400">
                €{result.vatAmount.toFixed(2)}
              </div>
            </div>
            <div class="text-center p-4 bg-white/80 dark:bg-gray-800/80 rounded-lg shadow-sm backdrop-blur-sm">
              <div class="text-sm text-gray-500 dark:text-gray-400">{t('grossAmount')}</div>
              <div class="text-2xl font-bold text-green-600 dark:text-green-400">
                €{result.grossAmount.toFixed(2)}
              </div>
            </div>
          </div>
        </div>
{/if}

      <div>
        <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-3">
          {t('euVatRates')}
        </h3>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead>
              <tr class="bg-gray-100 dark:bg-gray-700">
                <th class="px-3 py-2 text-left">{t('country')}</th>
                <th class="px-3 py-2 text-center">{t('standardRate')}</th>
                <th class="px-3 py-2 text-center">{t('reducedRates')}</th>
              </tr>
            </thead>
            <tbody>
              {#each Object.entries(vatRates).slice(0, 10) as [code, data] (code)}
<tr  class="border-b dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800">
                  <td class="px-3 py-2">{data.name}</td>
                  <td class="px-3 py-2 text-center font-medium">{data.standard}%</td>
                  <td class="px-3 py-2 text-center text-gray-500">
                    {data.reduced.length > 0 ? data.reduced.join('%, ') + '%' : '-'}
                  </td>
                </tr>
{/each}
            </tbody>
          </table>
        </div>
      </div>
    </div>
