// src/components/tools/WordCounter.tsx
'use client';

import { useState, useMemo } from 'react';
import { useTranslations } from 'next-intl';

export default function WordCounter() {
  const t = useTranslations('tools');
  const [text, setText] = useState('');

  const stats = useMemo(() => {
    const trimmed = text.trim();
    return {
      characters: text.length,
      charactersNoSpaces: text.replace(/\s/g, '').length,
      words: trimmed ? trimmed.split(/\s+/).length : 0,
      sentences: trimmed ? (trimmed.match(/[.!?]+/g) || []).length || (trimmed.length > 0 ? 1 : 0) : 0,
      paragraphs: trimmed ? trimmed.split(/\n\n+/).filter(p => p.trim()).length : 0,
      lines: trimmed ? trimmed.split('\n').length : 0,
    };
  }, [text]);

  return (
    <div className="space-y-4">
      <div>
        <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{t('input')}</label>
        <textarea
          className="tool-textarea h-64"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder={t('inputPlaceholder')}
        />
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <StatCard label={t('wordCounter.words')} value={stats.words} />
        <StatCard label={t('wordCounter.characters')} value={stats.characters} />
        <StatCard label={t('wordCounter.characters')} value={stats.charactersNoSpaces} />
        <StatCard label={t('wordCounter.sentences')} value={stats.sentences} />
        <StatCard label={t('wordCounter.paragraphs')} value={stats.paragraphs} />
        <StatCard label="Lines" value={stats.lines} />
      </div>

      <button
        onClick={() => setText('')}
        className="btn-secondary"
      >
        {t('clear')}
      </button>
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: number }) {
  return (
    <div className="p-4 bg-gray-100 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg text-center">
      <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">{value.toLocaleString()}</div>
      <div className="text-sm text-gray-600 dark:text-gray-300">{label}</div>
    </div>
  );
}

// src/components/tools/WordCounter.svelte
<script lang="ts">
  interface Props {
    locale: string;
    translations: Record<string, unknown>;
  }

  let { locale, translations }: Props = $props();

  // Translation helpers
  function t(key: string): string {
    const scope = translations['tools'] as Record<string, unknown> || {};
    const keys = key.split('.');
    let value: unknown = scope;
    for (const k of keys) { value = (value as Record<string, unknown>)?.[k]; }
    return typeof value === 'string' ? value : `MISSING: tools.${key}`;
  }

  let text = $state('');

  let stats = $derived.by(() => {
    const trimmed = text.trim();
    return {
      characters: text.length,
      charactersNoSpaces: text.replace(/\s/g, '').length,
      words: trimmed ? trimmed.split(/\s+/).length : 0,
      sentences: trimmed ? (trimmed.match(/[.!?]+/g) || []).length || (trimmed.length > 0 ? 1 : 0) : 0,
      paragraphs: trimmed ? trimmed.split(/\n\n+/).filter(p => p.trim()).length : 0,
      lines: trimmed ? trimmed.split('\n').length : 0,
    };
  });

</script>

{#snippet StatCard(label: string, value: number)}
  <div class="p-4 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg text-center">
    <div class="text-2xl font-bold text-amber-600 dark:text-amber-400">{value}</div>
    <div class="text-sm text-gray-600 dark:text-gray-300">{label}</div>
  </div>
{/snippet}


    <div class="space-y-4">
      <div>
        <label class="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{t('input')}</label>
        <textarea
          class="tool-textarea h-64"
          bind:value={text}
          placeholder={t('inputPlaceholder')}></textarea>
      </div>

      <div class="grid grid-cols-2 md:grid-cols-3 gap-4">
        {@render StatCard(t('wordCounter.words'), stats.words)}
        {@render StatCard(t('wordCounter.characters'), stats.characters)}
        {@render StatCard(t('wordCounter.characters'), stats.charactersNoSpaces)}
        {@render StatCard(t('wordCounter.sentences'), stats.sentences)}
        {@render StatCard(t('wordCounter.paragraphs'), stats.paragraphs)}
        {@render StatCard('Lines', stats.lines)}
      </div>

      <button
        onclick={() => text = ''}
        class="btn-secondary"
      >
        {t('clear')}
      </button>
    </div>
